### ISSUE TITLE
Mapping simple loop to cgra fails.

### ISSUE THREAD

**Issue by halfmanli** [ecolab-nus/morpher#9]
Here's my code:
--------------------------------------------------------------------------
#define CHAN_SIZE 3

#define row_size 80
#define col_size 80

__attribute__((noinline)) void scale_fxp(int *input, int *output) {
    for (int chan = 0; chan < CHAN_SIZE; chan++)
        for (int row = 0; row < row_size; row++)
            for (int col = 0; col < col_size; col++) {
#ifdef CGRA_COMPILER
                please_map_me();
#endif
                output[chan * row_size * col_size + row * col_size + col] =
                    input[chan * row_size * col_size + row * col_size + col] *
                    1.0 / 255;
            }
}

int main() {
    int *acc_input = malloc(sizeof(int) * row_size * col_size * CHAN_SIZE);
    int *acc_input_scaled =
        malloc(sizeof(int) * row_size * col_size * CHAN_SIZE);
    scale_fxp(acc_input, acc_input_scaled);
}
--------------------------------------------------------------------------
Here's my command: `python -u run_morpher.py cava_cgra/isp.c scale_fxp config/microspeech_hycube_mm_0.yaml`.
And the error is:
--------------------------------------------------------------------------
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
--------------------------------------------------------------------------

**Comment by zhaoying-LI** [comment]
This looks like caused by malloc. Could you please try to follow the way that the C code example we provide? such as gemm and arrar_add.

**Comment by halfmanli** [comment]
> This looks like caused by malloc. Could you please try to follow the way that the C code example we provide? such as gemm and arrar_add.

You're correct. It works after using array.
